@startuml
'https://plantuml.com/class-diagram

interface Animal {
  eat()
}
note right : somewhat like an abstract base class

class Rabbit {
  eat()
}

class Cat {
  eat()
}

class Dog {
  eat()
}

Animal <|-- Rabbit
Animal <|-- Dog
Animal <|-- Cat

@enduml