@startuml
'https://plantuml.com/class-diagram

abstract class OutputFormatter {
    +String format(String text)
}

class BorderFormatter {
    +String format(String text)
}
class LineWrapFormatter {
   +String format(String text)
}
class BSpracheFormatter {
   +String format(String text)
}

OutputFormatter <|-- BorderFormatter
OutputFormatter <|-- LineWrapFormatter
OutputFormatter <|-- BSpracheFormatter

@enduml